name: md2pptx
on: push
jobs:
  build-pptx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install python-pptx lib
        run: pip3 install python-pptx
      - name: Check md2pptx repo
        uses: actions/checkout@master
        with:
          repository: MartinPacker/md2pptx
      - run: pwd
      - run: ls -l
      - run: chmod +x md2pptx
      - run: python3 md2pptx output.pptx < input.md